### ISSUE TITLE
OSError: [Errno 18] Invalid cross-device link occurs on systems where /tmp is on a separate partition

### ISSUE THREAD

**Issue by ralienpp** [balena/python-pqueue#1]
My queue is initialized with a path like `/home/user/store`; pqueue's `_saveinfo` method creates a temporary file and then moves it to the directory in question.

It works fine if both, the source and the destination are on the same partition, but it fails if they're on different partitions. Here is a stack trace:

```
> pqueue.py(116)_saveinfo()
-> tmpfd, tmpfn = tempfile.mkstemp()
(Pdb) n
> pqueue.py(117)_saveinfo()
-> os.write(tmpfd, pickle.dumps(self.info))
(Pdb) n
> pqueue.py(118)_saveinfo()
-> os.close(tmpfd)
(Pdb) n
> pqueue.py(120)_saveinfo()
-> os.rename(tmpfn, self._infopath())
(Pdb) n
OSError: (18, 'Invalid cross-device link')
> /pqueue.py(120)_saveinfo()
-> os.rename(tmpfn, self._infopath())
(Pdb) pp tmpfn
'/tmp/tmpgGWKxT'
(Pdb) pp self._infopath()
u'/home/user/test/info'
```

Here's the output of `df -h`

```
user@machine ~/test $ df -h
Filesystem           Size  Used Avail Use% Mounted on
udev                 3.8G   12K  3.8G   1% /dev
tmpfs                779M  1.5M  777M   1% /run
/dev/sda1             30G   12G   17G  41% /
none                 4.0K     0  4.0K   0% /sys/fs/cgroup
none                 5.0M     0  5.0M   0% /run/lock
none                 3.8G  362M  3.5G  10% /run/shm
none                 100M   40K  100M   1% /run/user
/dev/sda3            881G  791G   45G  95% /home
/home/user/.Private  881G  791G   45G  95% /home/user
```

**Comment by balena** [comment]
Confirmed.

The mkstemp() parameter 'dir' should be used to indicate where to create 
the temporary file.

Ideally, it should go on the same directory as the pqueue storage.

A pending problem is what to do with garbage files that may possibly 
happen on the pqueue storage in this case.

**Comment by ralienpp** [comment]
Perhaps it can create those temporary files in a subdirectory - thus you can be certain that the data will be on the same partition.

Someone worried about leftovers can use a cron-job to clear those temporary files. A better alternative - pqueue can clear those leftovers when it starts up and initializes the persistent store (it should be easy, because it knows which subdirectory to clear). What do you think?

**Comment by balena** [comment]
'pqueue' may do a GC when it is initialized, but I think this is going 
to add too much complexity to the (simple) implementation.

We can leave the temporary directory as a initialization setting, so the 
user can manage this by himself.

**Comment by ralienpp** [comment]
Hi, I sent a pull request a while ago. Will you accept it?

**Comment by balena** [comment]
Regarding your patch, it seems promising. But I think it would be much better if the extra constructor parameter indicates the path where to store temp files, not a boolean where you force the '_temp' subdirectory or not.

**Comment by ralienpp** [comment]
I thought of that too. The rationale for choosing a boolean parameter was to simplify the interface for whoever uses the module.
- The temporary directory is an entity used internally by `pqueue` and higher-level modules don't need to be aware of the internals.
- Even if the path is passed directly, the caller can still give a path that is on a separate partition - so the problem will persist.

Maybe we could let them do that, but somewhere in the constructor an exception will be raised if the paths are on different partitions. This sounds more complex to me.

I see your point though, and I normally prefer things to be flexible - but in this case the flexibility gives people enough power to shoot themselves in the foot.

**Comment by balena** [comment]
Check if https://github.com/balena/python-pqueue/commit/5f67ca3ece235d57388276568c4e981ce9fdb789 suits you.

**Comment by ralienpp** [comment]
Yes, it does.

**Comment by balena** [comment]
The version 0.1.3 is now available at PyPI. Thanks for your input!

**Comment by MCOfficer** [comment]
i'm still getting a very similar error with 0.1.7:
```
Python 3.6.3 (default, Oct  3 2017, 21:45:48) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pqueue import Queue
>>> q = Queue("asdftest")
>>> q.put("foo")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/queue.py", line 143, in put
    self._put(item)
  File "/home/x/.local/lib/python3.6/site-packages/pqueue/pqueue.py", line 80, in _put
    self._saveinfo()
  File "/home/x/.local/lib/python3.6/site-packages/pqueue/pqueue.py", line 134, in _saveinfo
    os.rename(tmpfn, self._infopath())                                                                                                                                                                                                                                         
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmpc59bxy5b' -> 'asdftest/info' 
```
```
$ pip3 show pqueue
Name: pqueue
Version: 0.1.7
Summary: A single process, persistent multi-producer, multi-consumer queue.
```

**Comment by MCOfficer** [comment]
fixed it by replacing `os.rename` (pqueue.py, line 134) with `shutil.move` - i'm not sure if this will cause problems with posix, but it works fine for my simple script.
cheers!

**Comment by balena** [comment]
@MCOfficer : you just can't use a temp folder which is not on the same filesystem, or the file operations won't be atomic. I think this is already documented in the code, please check.

`shutil.move` is not a valid solution.

**Comment by MCOfficer** [comment]
welp, i just now realized one can just specify a different tempdir. blame my stupidity, i guess..
