### ISSUE TITLE
AttributeError: Queue instance has no attribute 'pop'

### ISSUE THREAD

**Issue by dweltvauller** [balena/python-pqueue#3]
Dear

First thank you for this module. I am using it but when I try the pop, this happens:

> > > from pqueue import Queue
> > > q = Queue("try")
> > > q.put(1)
> > > q.put('A')
> > > q.pop()
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > AttributeError: Queue instance has no attribute 'pop'
> > > q.get()
> > > 1
> > > q.get()
> > > 'A'

Anyway, is there a way to delete "get" data that I don't want to store anymore?

**Comment by balena** [comment]
There's no 'pop' in Queue class, please read https://docs.python.org/2/library/queue.html.

I think that the link above answers all your doubts. If not, contact me again.

---- federicohuman wrote ----

**Comment by balena** [comment]
Fixed the documentation.
