### ISSUE TITLE
Does not work on Windows

### ISSUE THREAD

**Issue by JokerQyou** [balena/python-pqueue#4]
The classification tags on  pypi page of this library indicate that it's `Operating System :: OS Independent`, but it does not work on Windows actually. I tested on Windows 10, either when you create a queue and start putting things into it, A `WindowsError 183` raises, or when you load a queue from existing file, the Unix-only function `os.ftruncate` being used will cause an `AttributeError` because, well, by definition there is no `os.ftruncate` on Windows.

**Comment by JokerQyou** [comment]
O sorry about missing environment information. I was testing with Python `2.7.11` 32 bit on Windows 10 64 bit.

The following code raises `WindowsError 183`:

``` python
import pqueue
q = pqueue.Queue('file')
q.put(1)
q.put(2)  # starting from the second put call it raises WindowsError 183 each time when you put
```

Yet I can still get from and put into the queue, seems like it just failed to sync to disk file.

And if you construct a queue from an existing file, you will see `AttributeError` immediately. This is actually documented in documentation of `os` module, it says `os.ftruncate` is Unix-only.

**Comment by balena** [comment]
You're correct. I shouldn't classify as OS independent, I'll rectify on pypi.

On the other hand, I'm wondering if the same would be useful on Windows. The inner atomic operation involved is 'rename', which also does not exist in Windows...

**Comment by JokerQyou** [comment]
Is it `os.rename` you were talking about? That does exist on Windows, as documented [here](https://docs.python.org/2/library/os.html#os.rename).

**Comment by JokerQyou** [comment]
But I think on Windows you cannot rename to a name which is already taken by an existing file. Better to move the file directly, I guess.

**Comment by balena** [comment]
I'm going to close this ticket after reclassifying the package as POSIX instead of OS Independent.

`os.rename` may be available on Windows, but behind the scenes (AFAIK) it won't perform atomic operations as in the `rename()` POSIX function. In order to correctly support Windows, more efforts will be needed to make sure about file operations atomicity.
